version: "3"
services:
  aerostracker-redis:
    container_name: aerostracker-redis
    image: redis:6-alpine
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - aerostracker-redisData:/data
    restart: always
  aerostracker-postgres:
    container_name: aerostracker-postgres
    image: postgres:12-alpine
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_DB=aerostracker
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - aerostracker-postgresData:/var/lib/postgresql/data
    restart: always
volumes:
  aerostracker-redisData:
  aerostracker-postgresData:
